packages:
  - admin
  - webcomponent

allowBuilds:
  '@parcel/watcher': true
  '@prisma/client': true
  '@prisma/engines': true
  better-sqlite3: true
  cypress: true
  esbuild: true
  prisma: true
  sharp: true
  vue-demi: true

ignoredBuiltDependencies:
  - cypress
