packages:
  - admin
  - webcomponent

ignoredBuiltDependencies:
  - cypress

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@prisma/client'
  - '@prisma/engines'
  - esbuild
  - prisma
  - sharp
  - vue-demi
